server:
  port: 9001

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
      auto: false
    credentials:
      useDefaultAwsCredentialsChain: true
      access-key:
      secret-key:
    end-point:
      uri: <QUEUE URI>
